feat: use bns-2 branch of connect
blockstack/todos pull request #72
Opened 2021-04-06 00:54 UTC by hstove

Uses version of `@stacks/connect` from https://github.com/blockstack/stacks-wallet-web/pull/1103

2021-04-09 13:23 UTC, markmhx requested changes

2021-04-09 13:23 UTC, markmhx commented on src/auth.js
> +    authOrigin: 'https://pr-1103.app.stacks.engineering/',
Do we want to hardcode this URL? Presumably that will mess things up upon deploy to todos.blockstack.org

2021-04-12 16:30 UTC, markmhx commented on src/auth.js
> +    authOrigin: 'https://pr-1103.app.stacks.engineering/',
Awaiting registrar on mainnet

2021-06-15 11:08 UTC, markmhx commented
It appears this PR should go back into development to update the `authOrigin` value above to `app.blockstack.org` if I'm not mistaken.

2021-06-28 20:49 UTC, markmhx commented
@fbwoolf to review and close if irrelevant now

2021-06-29 01:01 UTC, fbwoolf commented
I believe this is outdated am going to close. I don't see an existing branch in connect related to `bns-2`.

2021-06-29 01:01 UTC, closed without merging